services:
  api_host: "nomad-sadewasser.inl.local"
  api_base_path: "/nomad-oasis"
  admin_user_id: "2a497944-a042-45d1-9ec5-cd450c3d8950"

oasis:
  is_oasis: true
  uses_central_user_management: true
  allowed_users:
    - "diego.garzon@inl.int"
    - "sascha.sadewasser@inl.int"
    - "pedro.anacleto@inl.int"
    - "diogo.costa@inl.int"
    - "jose.fonseca@inl.int"
    - "nuno.rodrigues@inl.int"
    - "margarida.moura@inl.int"
    - "marina.alves@inl.int"
    - "joana.m.ribeiro@inl.int"
    - "andre.silva@inl.int"
    - "joao.p.oliveira@inl.int"
    - "gabriel.quartin@inl.int"
    - "pedro.sousa@inl.int"
    - "neha.kumari@inl.int"


plugins:
  entry_points:
    options:
      nomad_north_jupyter.north_tools:jupyter:
        id_url_safe: north-jupyter
        north_tool:
          image: ghcr.io/garzondiegofeup/nomad-oasis-inl/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://nomad-sadewasser.inl.local/nomad-oasis/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enabled: false

temporal:
  enabled: true

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
